Form page and Index with fixes
htmlacademy-adaptive/1681749-cat-energy-22 pull request #3
Opened 2021-03-31 18:11 UTC by agasnash

2021-04-01 21:49 UTC, tinakuzmenko requested changes
Немного не понял как обобщать стили. Посмотри еще раз внимательно на повторяющие элементы - они у тебя должны быть отдельными блоками.

2021-04-01 21:49 UTC, tinakuzmenko commented on source/index.html
> +      <h4 class="contacts__title">Приглашаем к сотрудничеству дилеров!</h4>
Обрати внимание!
У тебя не соблюдена иерархия заголовков - на странице есть `h1`, `h2` и `h4`, а `h3` отсутствует. Я бы сделала этот текст не заголовком, а просто параграфом.

2021-04-01 21:49 UTC, tinakuzmenko commented on source/form.html
> +    <section class="food-program">
Я бы не стала делить это на две отдельные секции. Ведь, по сути, это заголовок и описание все к той же самой форме.

2021-04-01 21:49 UTC, tinakuzmenko commented on source/form.html
> +          <ul class="basic-info__list-options">
Я думаю, список радио-кнопок нужно унести в другой `fieldset`

2021-04-01 21:49 UTC, tinakuzmenko commented on source/form.html
> +        <fieldset class="contacts-info">
Чем у тебя `basic-info` отличается от `contacts-info`? Ничем. Это два одинаковых филдсета. Так что давай мы им один и тот же класс зададим.

2021-04-01 21:49 UTC, tinakuzmenko commented on source/form.html
> +            <div class="contacts-info__icon">
Зачем оборачивать иконку в `div`?

2021-04-01 21:49 UTC, tinakuzmenko commented on source/form.html
> +        <fieldset class="comment-info">
Этот филдсет тоже желательно присоединить к первым трем в один и тот же класс

2021-04-01 21:49 UTC, tinakuzmenko commented on source/form.html
> +          <div class="comment-info__input">
Не нужно оборачивать в `div`

2021-04-01 21:49 UTC, tinakuzmenko commented on source/form.html
> +            <div class="basic-info__input form-input">
У нас запрещено на этом интенсиве стилизовать теги. Так что, давай мы лучше зададим класс `form-input` для инпута, а `form-label` для `label`

2021-04-01 21:49 UTC, tinakuzmenko commented on source/form.html
> +            <textarea name="comment" rows="8" cols="80">Расскажите обо всех повадках кота</textarea>
Это поле - самостоятельный блок.

2021-04-01 21:49 UTC, tinakuzmenko commented on source/form.html
> +        <fieldset class="additional-info">
Не нужен отдельный класс.

2021-04-01 21:49 UTC, tinakuzmenko commented on source/form.html
> +            <li class="additional-info__item" tabindex="0">
Здесь не нужен `tabindex`

2021-04-01 21:49 UTC, tinakuzmenko commented on source/form.html
> +              <input class="additional-info__checkbox" type="checkbox" name="sweetener" id="sweetener" checked>
Эти чекбоксы ты скроешь через visually-hidden, так что я бы не стала им какой-либо класс задавать. А вот лейблу - да.

2021-04-01 21:49 UTC, tinakuzmenko commented on source/form.html
> +        <button class="food-program__button" type="submit">Отправить заявку</button>
Почему у этой кнопки нет универсального класса? Ведь у тебя на главной точно такая же есть.

2021-04-05 14:22 UTC, tinakuzmenko requested changes
Не исправил то, о чем я просила в прошлый раз. Не могу принять.

2021-04-05 14:22 UTC, tinakuzmenko commented on source/form.html
> +        <fieldset class="basic-info block-title">
Почему у `fieldset` класс `block-title`?

2021-04-05 14:22 UTC, tinakuzmenko commented on source/form.html
> +        <fieldset class="basic-options">
Почему ты игнорируешь мои замечания? Я же просила все филдсеты сделать одним и тем же блоком.

2021-04-05 14:22 UTC, tinakuzmenko commented on source/form.html
> +              <label class="additional-info__label" for="milk">Молоко</label>
Чем этот `label` отличается от остальных?

2021-04-05 15:09 UTC, agasnash commented on source/form.html
> +        <fieldset class="basic-options">
то есть по мимо индивуального класса, задать один единый например form-block?

2021-04-05 19:40 UTC, tinakuzmenko approved these changes

2021-04-05 19:40 UTC, tinakuzmenko commented on source/form.html
> +              <label class="form-label form-label-type" for="weight">Вес (кг):*</label>
Не очень понимаю зачем тут класс `form-label-type`

2021-04-05 19:40 UTC, tinakuzmenko commented on source/form.html
> +              <label class="form-label form-label-select" for="add-weight">Набор массы</label>
Тут скорее уж `form-label--radio` будет. Типа модификатор для радио-инпутов.

2021-04-05 19:40 UTC, merged